<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Depa.Datalog.Core/Depa.Datalog.Core.csproj" />
    <ProjectReference Include="../../src/Depa.Datalog.Cozo/Depa.Datalog.Cozo.csproj" />
  </ItemGroup>
</Project>
