<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Depa.Datalog.Core/Depa.Datalog.Core.csproj" />
    <ProjectReference Include="../../src/Depa.Datalog.Cozo/Depa.Datalog.Cozo.csproj" />
    <ProjectReference Include="../../src/Depa.Ontology/Depa.Ontology.csproj" />
    <ProjectReference Include="../../src/Depa.Ontology.Portability.Yaml/Depa.Ontology.Portability.Yaml.csproj" />
    <ProjectReference Include="../../src/Depa.Ontology.Scripting.Jint/Depa.Ontology.Scripting.Jint.csproj" />
    <PackageReference Include="Depa.Cozo" Version="0.1.0" />
  </ItemGroup>
</Project>
